// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: doorman.proto

package zxdoorman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlgorithmPB_Kind int32

const (
	AlgorithmPB_NO_ALGORITHM AlgorithmPB_Kind = 0
	AlgorithmPB_STATIC       AlgorithmPB_Kind = 1
	AlgorithmPB_FAIR         AlgorithmPB_Kind = 2
)

// Enum value maps for AlgorithmPB_Kind.
var (
	AlgorithmPB_Kind_name = map[int32]string{
		0: "NO_ALGORITHM",
		1: "STATIC",
		2: "FAIR",
	}
	AlgorithmPB_Kind_value = map[string]int32{
		"NO_ALGORITHM": 0,
		"STATIC":       1,
		"FAIR":         2,
	}
)

func (x AlgorithmPB_Kind) Enum() *AlgorithmPB_Kind {
	p := new(AlgorithmPB_Kind)
	*p = x
	return p
}

func (x AlgorithmPB_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlgorithmPB_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_doorman_proto_enumTypes[0].Descriptor()
}

func (AlgorithmPB_Kind) Type() protoreflect.EnumType {
	return &file_doorman_proto_enumTypes[0]
}

func (x AlgorithmPB_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlgorithmPB_Kind.Descriptor instead.
func (AlgorithmPB_Kind) EnumDescriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{3, 0}
}

type Lease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpiryTime      int64 `protobuf:"varint,1,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	RefreshInterval int64 `protobuf:"varint,2,opt,name=refresh_interval,json=refreshInterval,proto3" json:"refresh_interval,omitempty"`
	Capacity        int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *Lease) Reset() {
	*x = Lease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{0}
}

func (x *Lease) GetExpiryTime() int64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *Lease) GetRefreshInterval() int64 {
	if x != nil {
		return x.RefreshInterval
	}
	return 0
}

func (x *Lease) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string                              `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Resource *GetCapacityRequest_ResourceRequest `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapacityRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetCapacityRequest) GetResource() *GetCapacityRequest_ResourceRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetCapacityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response   []*GetCapacityResponse_ResourceResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	Mastership *GetCapacityResponse_MasterShip         `protobuf:"bytes,2,opt,name=mastership,proto3" json:"mastership,omitempty"`
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapacityResponse) GetResponse() []*GetCapacityResponse_ResourceResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetCapacityResponse) GetMastership() *GetCapacityResponse_MasterShip {
	if x != nil {
		return x.Mastership
	}
	return nil
}

type AlgorithmPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind               AlgorithmPB_Kind             `protobuf:"varint,1,opt,name=kind,proto3,enum=doorman.AlgorithmPB_Kind" json:"kind,omitempty"`
	LeaseLength        int64                        `protobuf:"varint,2,opt,name=lease_length,json=leaseLength,proto3" json:"lease_length,omitempty"` // zx algo data
	RefreshInterval    int64                        `protobuf:"varint,3,opt,name=refresh_interval,json=refreshInterval,proto3" json:"refresh_interval,omitempty"`
	LearningModeLength int64                        `protobuf:"varint,4,opt,name=learning_mode_length,json=learningModeLength,proto3" json:"learning_mode_length,omitempty"`
	Parameters         []*AlgorithmPB_NamedParamter `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *AlgorithmPB) Reset() {
	*x = AlgorithmPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlgorithmPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmPB) ProtoMessage() {}

func (x *AlgorithmPB) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmPB.ProtoReflect.Descriptor instead.
func (*AlgorithmPB) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{3}
}

func (x *AlgorithmPB) GetKind() AlgorithmPB_Kind {
	if x != nil {
		return x.Kind
	}
	return AlgorithmPB_NO_ALGORITHM
}

func (x *AlgorithmPB) GetLeaseLength() int64 {
	if x != nil {
		return x.LeaseLength
	}
	return 0
}

func (x *AlgorithmPB) GetRefreshInterval() int64 {
	if x != nil {
		return x.RefreshInterval
	}
	return 0
}

func (x *AlgorithmPB) GetLearningModeLength() int64 {
	if x != nil {
		return x.LearningModeLength
	}
	return 0
}

func (x *AlgorithmPB) GetParameters() []*AlgorithmPB_NamedParamter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ResourcePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentiferGlob string `protobuf:"bytes,1,opt,name=identifer_glob,json=identiferGlob,proto3" json:"identifer_glob,omitempty"`
	Capacity      int32  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SafeCapacity  int32  `protobuf:"varint,3,opt,name=safe_capacity,json=safeCapacity,proto3" json:"safe_capacity,omitempty"`
	// zx resource has a algorithm, but algorithm can be use
	Algo        *AlgorithmPB `protobuf:"bytes,4,opt,name=algo,proto3" json:"algo,omitempty"`
	Description string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ResourcePB) Reset() {
	*x = ResourcePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourcePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePB) ProtoMessage() {}

func (x *ResourcePB) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePB.ProtoReflect.Descriptor instead.
func (*ResourcePB) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{4}
}

func (x *ResourcePB) GetIdentiferGlob() string {
	if x != nil {
		return x.IdentiferGlob
	}
	return ""
}

func (x *ResourcePB) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ResourcePB) GetSafeCapacity() int32 {
	if x != nil {
		return x.SafeCapacity
	}
	return 0
}

func (x *ResourcePB) GetAlgo() *AlgorithmPB {
	if x != nil {
		return x.Algo
	}
	return nil
}

func (x *ResourcePB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ResourceRepository struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*ResourcePB `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ResourceRepository) Reset() {
	*x = ResourceRepository{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRepository) ProtoMessage() {}

func (x *ResourceRepository) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRepository.ProtoReflect.Descriptor instead.
func (*ResourceRepository) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceRepository) GetResources() []*ResourcePB {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetCapacityRequest_ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Priority   int32  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Has        *Lease `protobuf:"bytes,3,opt,name=has,proto3" json:"has,omitempty"`
	Want       int32  `protobuf:"varint,4,opt,name=want,proto3" json:"want,omitempty"`
}

func (x *GetCapacityRequest_ResourceRequest) Reset() {
	*x = GetCapacityRequest_ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapacityRequest_ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest_ResourceRequest) ProtoMessage() {}

func (x *GetCapacityRequest_ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest_ResourceRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest_ResourceRequest) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCapacityRequest_ResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetCapacityRequest_ResourceRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GetCapacityRequest_ResourceRequest) GetHas() *Lease {
	if x != nil {
		return x.Has
	}
	return nil
}

func (x *GetCapacityRequest_ResourceRequest) GetWant() int32 {
	if x != nil {
		return x.Want
	}
	return 0
}

type GetCapacityResponse_ResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId   string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Gets         *Lease `protobuf:"bytes,2,opt,name=gets,proto3" json:"gets,omitempty"`
	SafeCapacity int32  `protobuf:"varint,3,opt,name=safe_capacity,json=safeCapacity,proto3" json:"safe_capacity,omitempty"`
}

func (x *GetCapacityResponse_ResourceResponse) Reset() {
	*x = GetCapacityResponse_ResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapacityResponse_ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse_ResourceResponse) ProtoMessage() {}

func (x *GetCapacityResponse_ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse_ResourceResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse_ResourceResponse) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetCapacityResponse_ResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetCapacityResponse_ResourceResponse) GetGets() *Lease {
	if x != nil {
		return x.Gets
	}
	return nil
}

func (x *GetCapacityResponse_ResourceResponse) GetSafeCapacity() int32 {
	if x != nil {
		return x.SafeCapacity
	}
	return 0
}

type GetCapacityResponse_MasterShip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterAddress string `protobuf:"bytes,1,opt,name=master_address,json=masterAddress,proto3" json:"master_address,omitempty"`
}

func (x *GetCapacityResponse_MasterShip) Reset() {
	*x = GetCapacityResponse_MasterShip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapacityResponse_MasterShip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse_MasterShip) ProtoMessage() {}

func (x *GetCapacityResponse_MasterShip) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse_MasterShip.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse_MasterShip) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetCapacityResponse_MasterShip) GetMasterAddress() string {
	if x != nil {
		return x.MasterAddress
	}
	return ""
}

type AlgorithmPB_NamedParamter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AlgorithmPB_NamedParamter) Reset() {
	*x = AlgorithmPB_NamedParamter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doorman_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlgorithmPB_NamedParamter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmPB_NamedParamter) ProtoMessage() {}

func (x *AlgorithmPB_NamedParamter) ProtoReflect() protoreflect.Message {
	mi := &file_doorman_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmPB_NamedParamter.ProtoReflect.Descriptor instead.
func (*AlgorithmPB_NamedParamter) Descriptor() ([]byte, []int) {
	return file_doorman_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AlgorithmPB_NamedParamter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlgorithmPB_NamedParamter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_doorman_proto protoreflect.FileDescriptor

var file_doorman_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x22, 0x6f, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x22, 0x81, 0x02, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x47, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x1a, 0x84, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x68, 0x61, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x4c,
	0x65, 0x61, 0x73, 0x65, 0x52, 0x03, 0x68, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x77, 0x61, 0x6e, 0x74, 0x22, 0xdc, 0x02,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x0a, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x68, 0x69, 0x70, 0x52, 0x0a, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x1a, 0x7c, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x04, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64,
	0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x04, 0x67, 0x65,
	0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x66, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x66, 0x65, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x1a, 0x33, 0x0a, 0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x68, 0x69, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xeb, 0x02, 0x0a,
	0x0b, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x50, 0x42, 0x12, 0x2d, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x64, 0x6f, 0x6f,
	0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x50, 0x42,
	0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x29,
	0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4d, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x42, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x50, 0x42, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a,
	0x39, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x74, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x52, 0x49, 0x54,
	0x48, 0x4d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x52, 0x10, 0x02, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x42, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x65, 0x72, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x65, 0x72, 0x47, 0x6c, 0x6f, 0x62,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x61, 0x66, 0x65, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x50, 0x42, 0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a,
	0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x42, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x32, 0x54, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x74, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x2f, 0x7a, 0x78, 0x64, 0x6f, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doorman_proto_rawDescOnce sync.Once
	file_doorman_proto_rawDescData = file_doorman_proto_rawDesc
)

func file_doorman_proto_rawDescGZIP() []byte {
	file_doorman_proto_rawDescOnce.Do(func() {
		file_doorman_proto_rawDescData = protoimpl.X.CompressGZIP(file_doorman_proto_rawDescData)
	})
	return file_doorman_proto_rawDescData
}

var file_doorman_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_doorman_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_doorman_proto_goTypes = []interface{}{
	(AlgorithmPB_Kind)(0),                        // 0: doorman.AlgorithmPB.Kind
	(*Lease)(nil),                                // 1: doorman.Lease
	(*GetCapacityRequest)(nil),                   // 2: doorman.GetCapacityRequest
	(*GetCapacityResponse)(nil),                  // 3: doorman.GetCapacityResponse
	(*AlgorithmPB)(nil),                          // 4: doorman.AlgorithmPB
	(*ResourcePB)(nil),                           // 5: doorman.ResourcePB
	(*ResourceRepository)(nil),                   // 6: doorman.ResourceRepository
	(*GetCapacityRequest_ResourceRequest)(nil),   // 7: doorman.GetCapacityRequest.ResourceRequest
	(*GetCapacityResponse_ResourceResponse)(nil), // 8: doorman.GetCapacityResponse.ResourceResponse
	(*GetCapacityResponse_MasterShip)(nil),       // 9: doorman.GetCapacityResponse.MasterShip
	(*AlgorithmPB_NamedParamter)(nil),            // 10: doorman.AlgorithmPB.NamedParamter
}
var file_doorman_proto_depIdxs = []int32{
	7,  // 0: doorman.GetCapacityRequest.resource:type_name -> doorman.GetCapacityRequest.ResourceRequest
	8,  // 1: doorman.GetCapacityResponse.response:type_name -> doorman.GetCapacityResponse.ResourceResponse
	9,  // 2: doorman.GetCapacityResponse.mastership:type_name -> doorman.GetCapacityResponse.MasterShip
	0,  // 3: doorman.AlgorithmPB.kind:type_name -> doorman.AlgorithmPB.Kind
	10, // 4: doorman.AlgorithmPB.parameters:type_name -> doorman.AlgorithmPB.NamedParamter
	4,  // 5: doorman.ResourcePB.algo:type_name -> doorman.AlgorithmPB
	5,  // 6: doorman.ResourceRepository.resources:type_name -> doorman.ResourcePB
	1,  // 7: doorman.GetCapacityRequest.ResourceRequest.has:type_name -> doorman.Lease
	1,  // 8: doorman.GetCapacityResponse.ResourceResponse.gets:type_name -> doorman.Lease
	2,  // 9: doorman.Capacity.GetCapacity:input_type -> doorman.GetCapacityRequest
	3,  // 10: doorman.Capacity.GetCapacity:output_type -> doorman.GetCapacityResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_doorman_proto_init() }
func file_doorman_proto_init() {
	if File_doorman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doorman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapacityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapacityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlgorithmPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourcePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRepository); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapacityRequest_ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapacityResponse_ResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapacityResponse_MasterShip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doorman_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlgorithmPB_NamedParamter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doorman_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doorman_proto_goTypes,
		DependencyIndexes: file_doorman_proto_depIdxs,
		EnumInfos:         file_doorman_proto_enumTypes,
		MessageInfos:      file_doorman_proto_msgTypes,
	}.Build()
	File_doorman_proto = out.File
	file_doorman_proto_rawDesc = nil
	file_doorman_proto_goTypes = nil
	file_doorman_proto_depIdxs = nil
}
