// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: doorman.proto

package zxdoorman

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CapacityClient is the client API for Capacity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapacityClient interface {
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error)
}

type capacityClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityClient(cc grpc.ClientConnInterface) CapacityClient {
	return &capacityClient{cc}
}

func (c *capacityClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error) {
	out := new(GetCapacityResponse)
	err := c.cc.Invoke(ctx, "/doorman.Capacity/GetCapacity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityServer is the server API for Capacity service.
// All implementations must embed UnimplementedCapacityServer
// for forward compatibility
type CapacityServer interface {
	GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error)
	mustEmbedUnimplementedCapacityServer()
}

// UnimplementedCapacityServer must be embedded to have forward compatible implementations.
type UnimplementedCapacityServer struct {
}

func (UnimplementedCapacityServer) GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedCapacityServer) mustEmbedUnimplementedCapacityServer() {}

// UnsafeCapacityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityServer will
// result in compilation errors.
type UnsafeCapacityServer interface {
	mustEmbedUnimplementedCapacityServer()
}

func RegisterCapacityServer(s grpc.ServiceRegistrar, srv CapacityServer) {
	s.RegisterService(&Capacity_ServiceDesc, srv)
}

func _Capacity_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doorman.Capacity/GetCapacity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capacity_ServiceDesc is the grpc.ServiceDesc for Capacity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capacity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doorman.Capacity",
	HandlerType: (*CapacityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapacity",
			Handler:    _Capacity_GetCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doorman.proto",
}
